name: http_clients
description: Quickly compose http client
version: 0.1.0
repository: https://github.com/predatorx7/http_clients

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.0.0
  http: ^0.13.0
  meta: ^1.0.0

dev_dependencies:
  benchmark_harness: ^2.2.1
  build_runner: ^2.3.3
  lints: ^2.0.0
  mockito: ^5.4.0
  test: ^1.21.0
  http_client_conformance_tests:
    git: 
      url: https://github.com/dart-lang/http.git
      path: pkgs/http_client_conformance_tests/
      # pre dart 3.0 conformance test
      ref: f581ff7
