name: http_clients
description: Quickly compose http client
version: 0.1.0
repository: https://github.com/predatorx7/http_clients

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  http: ^0.13.6
  meta: ^1.9.1

dev_dependencies:
  benchmark_harness: ^2.2.1
  build_runner: ^2.3.3
  lints: ^2.0.0
  mockito: ^5.4.0
  test: ^1.21.0
  http_client_conformance_tests:
    git: 
      url: https://github.com/dart-lang/http.git
      path: pkgs/http_client_conformance_tests/

